### ISSUE TITLE
Blade directive inside any comment causes Blade to try and parse it as uncommented and crashes.

### ISSUE THREAD

**Issue by televators** [EFTEC/BladeOne#161]
### Issue
In *any* kind of Blade/PHP comment, if I write a Blade directive (`@foreach` in my case) the compiler is mysteriously forgetting it's inside a comment and trying to parse it, which throws a critical error in the original instance.

Spent like an hour and a half rebooting my containers, laptop, and VS Code trying to figure out why my WordPress project was getting a critical error on a template. Once I figured it out with Ol' Reliable (uncommenting line by line; my error logs were acting up at the same time 🤷), I tested various comment types. All have same result.

Blade comment:
```
{{--
  Lorem ipsum dolor @foreach
--}}
```
Multi line comment in PHP tags
```
@php
  /**
   * Lorem ipsum dolor @foreach
   */
@endphp
```
Single line comment in PHP tags
```
@php
  // Lorem ipsum dolor @foreach
@endphp
```
I also tried with other @directives and got similar results. This results in the line directly after the comment to be echoed to the DOM:
```
// @include
$previous_layout =  null;
```
Results in `$previous_layout = null; $current_layout = null; ?>` being printed in the middle of my markup in the browser.

---
I'm not using BladeOne directly exactly; I'm using dievardump/wp-bladeone-plugin which hasn't been updated in a while and I've not experienced this issue until last night. That repo is using ^3.46 of BladeOne. I've got other directive blocks commented out with `{{-- --}}` comments above and below the one that had the `@foreach` so I'm really not sure what's happening.
I don't submit issues often so anything else I should include, let me know. Thanks!

**Comment by jorgecc** [comment]
ok, solved in #4.5.3

4.5.3, the templates are binary compatible with 3.x however, it requires PHP 7.2 and higher.   Since PHP 5.6 is long dead, then I decided to plug the cord. PHP 7.2 is also discontinued but it is still supported.

**Comment by televators** [comment]
Woohoo! Thanks, dude. Yeah the wp-blade-one plugin is very outdated and unmaintained now but it was still getting the job done. Going to have to spin up my own drop-in integration with current version of BladeOne.
